sudo: false
language: cpp

env:
  global:
    - LLVM_VERSION=3.8.0
    # Maintenance note: to move to a new version
    # of boost, update both BOOST_ROOT and BOOST_URL.
    # Note that for simplicity, BOOST_ROOT's final
    # namepart must match the folder name internal
    # to boost's .tar.gz.
    - LCOV_ROOT=$HOME/lcov
    - BOOST_ROOT=$HOME/boost_1_67_0
    - BOOST_URL='http://sourceforge.net/projects/boost/files/boost/1.67.0/boost_1_67_0.tar.gz'

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages:
      - gcc-5
      - g++-5
      - python-software-properties
      - protobuf-compiler
      - libprotobuf-dev
      - libssl-dev
      - libstdc++6
      - binutils-gold
      - cmake
      - lcov
      - gdb

matrix:
  include:
    - compiler: gcc
      env:
      - GCC_VER=5
      - BUILD_TYPE=Debug
      - PARALLEL_TESTS='false'
      - CMAKE_EXTRA_ARGS='-Werr=ON -Dcoverage=ON'
      - PATH=$PWD/cmake/bin:$PATH
      - APP=divvylibppdemo

cache:
  directories:
  - $BOOST_ROOT

before_install:
  - ( cd extras/divvyd && bin/ci/ubuntu/install-dependencies.sh ../.. )

script:
  - extras/divvyd/bin/ci/ubuntu/build-and-test.sh

notifications:
  email:
    false
  irc:
    channels:
      - "chat.freenode.net#divvy-dev"

